
CREATE ROLE admins
CREATE ROLE users

CREATE USER admin1 WITH PASSWORD 'admin_password'
CREATE USER user1 WITH PASSWORD 'user_password'

GRANT admins TO admin1
GRANT users TO user1

GRANT CONNECT ON DATABASE staff TO admins
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admins

GRANT CONNECT ON DATABASE staff TO users
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO users

